### ISSUE TITLE
Adding a second GPU has caused OpenCL renderer to fail for editing.

### ISSUE THREAD

**Issue by EmpiresBane** [mfeemster/fractorium#13]
After adding a second GPU, I can no longer use OpenCL for editing. Oddly, it works fine for the final render. When I select "Use OpenCL", it creates a dialog saying "Could not create requested renderer, fallback CPU renderer created. See info tab for details." Then a second, saying "Error creating renderer, most likely a GPU problem. Using CPU instead."

In the info tab, it returns this text:
````
ERROR: Invalid operation in cl::Context().

Error initializing OpenCL renderer, using CPU renderer instead.
````

This is using version 0.4.1.8.

I assume the reason for this is because these cards are not in SLI. I have a GTX 780ti and GTX 670. They run separately from each other, driving different monitors.

**Comment by gh2k** [comment]
I had a problem running Fractorium on my machine with 2 GPUs on Linux, with those same symptoms. (Cards are in crossfire but still show up separately to Fractorium)

My solution was to set opencl to use the card which did not have a monitor attached. That may not work for you if you have monitors connected to both, but what happens if you enable the other card for opencl instead?

Also, is the fractorium window displaying on the screen driven by the card you selected? Does that make a difference?

**Comment by mfeemster** [comment]
I'm sorry to hear this happened. gh2k is the only person who has managed to get this to work. I do not have a dual GPU setup so I cannot test this scenario. Perhaps it's something I'll look into in the future after I get through my long list of features I'm currently working on.

**Comment by EmpiresBane** [comment]
> My solution was to set opencl to use the card which did not have a monitor attached. That may not work for you if you have monitors connected to both, but what happens if you enable the other card for opencl instead?

So I just did some testing, and even when both monitors are connected to the same card, I get the same error. I then tried running with only a single monitor. Didn't matter which GPU I tried rendering with. I just got access to VS 2013 Professional through my school, so I'll mess around, see if I can figure out what's up. Probably won't be able to, though.

**Comment by mfeemster** [comment]
If you attempt to build, you can save yourself a lot of time by following the build instructions on the wiki. Although I wouldn't recommend doing it, as you'll lose at least a weekend on it.

I really need to get on the dual GPU stuff, but it's just a matter of plunking down another $300 and allocating some time for it.

**Comment by mfeemster** [comment]
EmpiresBane,

I wanted to let you know that I now have two GPUs in my machine and will be working on multi-gpu support over the next few weeks. It'll be included in the next release. Sorry about the long delay.

**Comment by mfeemster** [comment]
All,

I have implemented multi-GPU support across the entire project. So it works on the command line and in the GUI.

I do not have a release executable ready yet, as I'm still adding more features before I do a release. But if you want to build from source, you will be able to run with more than one GPU. If you take that route, please follow the build instructions on the wiki.
