### ISSUE TITLE
Delightful!

### ISSUE THREAD

**Issue by gambhiro** [mfeemster/fractorium#30]
I'm so glad to have discovered this! Apophysis is just lagging too much over wine. I've just made [this one](http://erethedaybreak.deviantart.com/art/How-was-your-walk-574168962), running the Fractorium beta with wine, it was a delight to use!

Only CPU, but still it was great to see it actually spins up all the cores.

**Comment by mfeemster** [comment]
Glad you like it! See me on either of these two places:

https://www.facebook.com/groups/Fractorium/
http://mfeemster.deviantart.com/

Check the journal entry on DA, make sure you have the latest version, 0.9.9.2
