### ISSUE TITLE
Linux binary

### ISSUE THREAD

**Issue by gambhiro** [mfeemster/fractorium#31]
Is there any chance for a Linux x64 binary? Or else, how do I compile it on Linux?

The beta ran well with wine, but only CPU. I'm looking forward to see to see it fly with GPU access too.

I'm not a stranger to manually compiling stuff, but some pointers would help to get started. I see `Data/Wiki/Building.htm` is from `Jul 8, 2014`, do you have a much different build process these days?

**Comment by mfeemster** [comment]
I regularly confirm the project builds on Linux with GPU support. Sadly, I have no official build steps yet because I focus mainly on Windows. However, I did post a rough write-up as a comment below this post:

http://mfeemster.deviantart.com/journal/Fractorium-Beta-0-9-9-0-Released-561330048

It seemed to work for the person I wrote it for. Give it a try. I welcome any contributions, such as a build script or condensing/cleanup of those steps.

**Comment by gambhiro** [comment]
OK, coming along. I got it to build and run in Qt Creator, but OpenCL is not enabled.

I installed `opencl-headers`, `nvidia-opencl-dev`, `nvidia-opencl-icd-352`. There are no warnings about missing linked libs during compilation.

I saw in `build_all.sh` that you have a config variable for nvidia, so I added `CONFIG=nvidia` to the env. vars. in Qt Creator but that didn't do the trick.

Perhaps this isn't how you compile it?

**Comment by mfeemster** [comment]
I'm not even sure if that nvidia config option is still needed, it was a legacy OpenCL thing. I'd have to look at it again.

You need to make sure you have your drivers installed. I've found that doing so on linux is nearly impossible. Help on that is beyond the scope of what I can offer.

**Comment by mfeemster** [comment]
Can you also build the command line program EmberRender in QtCreator? Then run it with nothing but the option --openclinfo and see what it outputs. That will tell you if there is even an OpenCL driver loaded on your system, and what devices it sees.

**Comment by gambhiro** [comment]
Success! It needed some symlinks for it to find OpenCL (other test programs too, not just Fractorium). 

Strangely enough it was really slow when I turned OpenCL on, but I'd like to do more testing to find out why.

This [SO answer](http://stackoverflow.com/a/33483311/195141) had the key:

```
sudo apt-get install nvidia-352 nvidia-352-dev nvidia-prime nvidia-modprobe
sudo ln -s /usr/include/nvidia-352/GL /usr/local/include
sudo ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 /usr/local/lib/libOpenCL.so
```

I would like to help to make it easy for people to install this, what do you think about a Launchpad PPA for Fractorium? If you create one for Fractorium, I would like to find out how to package it and submit to a PPA. It would be a learning experience for me too, but I'm thinking it can't be too hard.

**Comment by mfeemster** [comment]
Glad to hear it worked. I eventually want to make a Linux package but I will be unavailable for the next 2 weeks. I also have further work to do on the code after that, so it would have to wait until sometime next year. I am totally clueless when it comes to Linux and was only able to get this to build due to QtCreator holding my hand the whole way through. If you would like to get a package going, I would welcome the help. Email me and we can coordinate. Thanks.

**Comment by gh2k** [comment]
Sorry for extended absence. I was in-progress with creating a debian package for Fractorium when crazy things started happening with paid-for job. :)

I can pick it up again, but if you're having fun I don't want to step on your toes @gambhiro

**Comment by gambhiro** [comment]
Hi @gh2k, I read up on the docs and got a debian package going. I tried on a testing PPA on Launchpad, the autobuild succeeds for amd64.

@mfeemster asked to put it on hold for now while he is on vacation, he said he would like to review how this works, so I suppose we'll pick it up when he's back.

**Comment by gh2k** [comment]
Righto. That's nice. :) Are you building against Qt5? I had issues with dependencies as there wasn't a stable qt5 package in Ubuntu. I haven't looked at the latest version though.

**Comment by mfeemster** [comment]
I am back. What is the status of this? I definitely would like to get the scripts to create the installer committed to the project, that way I can build a new one with each release.

**Comment by gambhiro** [comment]
I was building on Ubuntu Vivid, qt5-default is at 5.4.1 there. Qt 5.5 is apparently coming next year April in Xenial.

**Comment by gambhiro** [comment]
A follow-up comment on [DA](http://comments.deviantart.com/1/561330048/3953000026) would be good too, and MickHogan might be interested in testing as well.

**Comment by mfeemster** [comment]
For sure, I will post a new journal entry once we have this solid.
