### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by kochd** [mfeemster/fractorium#37]
Buildsystem for Linux is missing cl.hpp in the following locations 
<pre>
Builds/QtCreator/EmberCL
Builds/QtCreator/EmberAnimate/
Builds/QtCreator/EmberGenome/
Builds/QtCreator/EmberRender/
Builds/QtCreator/Fractorium/
</pre>

I fixed it by sym linking

**Comment by mfeemster** [comment]
Hi Daniel,

We include it here:

https://github.com/mfeemster/fractorium/tree/master/Deps/CL

Is that folder not added to the include paths? I thought we did that quite a while ago. If not, that's definitely a build bug that I'll try to fix soon.

On that note, we are working on making a linux package installer, so hopefully nobody will have to build from source in the near future.

**Comment by gambhiro** [comment]
#38 should fix it.

**Comment by gambhiro** [comment]
@kochd Please `git pull` and try again. I updated the dependency notes in the README too.

```
sudo apt-get install g++ libdbus-1-dev libgl1-mesa-dev libgl-dev libglm-dev libjpeg-dev libpng12-dev libtbb-dev libxml2-dev qt5-default qt5-qmake qtbase5-dev libqt5opengl5-dev ocl-icd-libopencl1
```

Please let us know if it still fails.

**Comment by mfeemster** [comment]
@kochd Can you please confirm whether this is fixed or not? I'd like to close this out.
