### ISSUE TITLE
Launchpad Team PPA

### ISSUE THREAD

**Issue by gambhiro** [mfeemster/fractorium#39]
I would like to suggest a Launchpad Team PPA. (There are a multitude of these but [deluge-team](https://launchpad.net/~deluge-team/+archive/ubuntu/ppa) comes to mind as an example).

If @mfeemster would create one for fractorium, he could authorize people to maintain packages there.

**Comment by mfeemster** [comment]
This sounds like a good idea. I will look at that soon when I get free moment.

**Comment by gambhiro** [comment]
Please also consider if you would like to extend the package description. This is in `debian/control`, which has atm:

```
 A Qt-based fractal flame editor which uses a C++ re-write of the flam3
 algorithm named Ember and a GPU capable version named EmberCL which implements
 a portion of the cuburn algorithm in OpenCL.
 .
 The interface is very similar to Apophysis, with most of the popular variations
 implemented.
```

**Comment by gambhiro** [comment]
I CAN HAS [Ubuntu Fractorium PPA](https://launchpad.net/~fractorium/+archive/ubuntu/ppa).
