### ISSUE TITLE
panning tool

### ISSUE THREAD

**Issue by gambhiro** [mfeemster/fractorium#41]
A panning-only tool would be useful, which would move the Center X and Y parameters.

Ideally, shifting the view without triggering a re-render.

**Comment by mfeemster** [comment]
You can do this by pressing the middle mouse button down and dragging:

https://github.com/mfeemster/fractorium/wiki/Fractorium-User-Guide

Doing it without triggering a re-render would be a lot of work without offering much value and is beyond the scope of what I'm working on right now.

Is this sufficient?

**Comment by gambhiro** [comment]
Thanks, I didn't discover that.
