### ISSUE TITLE
slow OpenCL on Nvidia Quadro K1100M

### ISSUE THREAD

**Issue by gambhiro** [mfeemster/fractorium#42]
I need some help to find out if this is the driver, the hardware or perhaps a bug.

The signs are that OpenCL is working, but the effect is longer render times, not faster.

With the "CL" button off, I see the CPU cores spin up during render. When the "CL" button is on, the CPU stays quiet and the `nvidia-settings` tool reports that the GPU use jumps up.

```
$ emberrender --openclinfo                                                   

OpenCL Info: 
Platform 0: NVIDIA Corporation NVIDIA CUDA OpenCL 1.2 CUDA 7.5.23
Device 0: NVIDIA Corporation Quadro K1100M
CL_DEVICE_OPENCL_C_VERSION: OpenCL C 1.2 
CL_DEVICE_LOCAL_MEM_SIZE: 49,152
CL_DEVICE_LOCAL_MEM_TYPE: 1
CL_DEVICE_MAX_COMPUTE_UNITS: 2
CL_DEVICE_MAX_READ_IMAGE_ARGS: 256
CL_DEVICE_MAX_WRITE_IMAGE_ARGS: 16
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 536,821,760
CL_DEVICE_ADDRESS_BITS: 64
CL_DEVICE_GLOBAL_MEM_CACHE_TYPE: 2
CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE: 128
CL_DEVICE_GLOBAL_MEM_CACHE_SIZE: 32,768
CL_DEVICE_GLOBAL_MEM_SIZE: 2,147,287,040
CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE: 65,536
CL_DEVICE_MAX_CONSTANT_ARGS: 9
CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS: 3
CL_DEVICE_MAX_WORK_GROUP_SIZE: 1,024
CL_DEVICE_MAX_WORK_ITEM_SIZES: 1,024, 1,024, 64
```

[ratGPU](http://ratgpu.com/) displays a warning:

```
W: The device NVIDIA Corporation : NVIDIA CUDA : Quadro K1100M does not support SPIR 1.2, so it will be ignored.
```

Would this be the blocking issue?

It get the impression that SPIR support is tied to the driver version, is that correct?

**Comment by mfeemster** [comment]
I don't use SPIR, instead I compile the program at runtime.

I've had numerous problems with Nvidia with wildly varying OpenCL performance with their drivers. As a company they don't like OpenCL because it competes with (and is better than) CUDA. So I suspect they do it on purpose. I looked up the specs for that card and they are sort of weak with 384 cores, however it should still be faster than the CPU. I did much of the original development of Fractorium with a GTX460 which also has 384 cores and it was always better than the CPU.

Next to the CL button is SP/DP. Use SP because DP is always much much slower on the GPU. For CPU, there is almost no difference so go with DP there.

Aside from that, there's nothing we can do, this is Nvidia's problem.

When you say longer render times, are you saying that while dragging around the interactive render, the CPU gives better feedback? Also look at the iters/sec measurement on the bottom status bar. Do you get a higher number there for the CPU? If so, there is something severely wrong with that card/driver.

**Comment by gh2k** [comment]
I think CUDA is much more closely matched to their hardware. Launching kernels is more involved as it forces you to spend a long time making sure your memory is organised well and you're launching the right number of threads for the number of cores you have, and ensuring that they read memory contiguously. They also provide some pretty good free tools for profiling what you've done.

As a result I think it's a lot harder to write general-purpose code but when you do optimise it properly it runs extremely fast. I'm not sure how well suited the platform would be to the way Ember builds its programs... I can't imagine creating a CUDA-compatible version being a trivial task by any stretch.

**Comment by mfeemster** [comment]
I've seen tests where OpenCL gives comparable results to CUDA on older drivers where Nvidia didn't deliberately cripple them.

The kernel launches are very quick and are a negligible amount of overhead relative to the amount of computation done within each kernel.

CUDA is incompatible with Ember, and fractal flames in general because it doesn't support runtime compilation. I initially went down the CUDA path when I began the GPU work in late 2012/early 2013 to see if it was possible. I posted on their forums and confirmed that there is no way CUDA could do what I needed. So it's not that doing it in CUDA is non-trivial, rather, it's impossible.

OpenCL is a superior system for this project due to its runtime compilation and cross-hardware support.

A few things to test:

-Is the slowness only seen in the interactive renderer, or does it persist during a final render?

-I've found that if you have the tabs on the main window docked on both the left and right side, and the image is larger than the space in between them (scrollbars will show up), then interactive rendering becomes very slow. I believe it has something to do with the way Qt is trying to refresh the screen. It's something I haven't been able to resolve.

**Comment by gambhiro** [comment]
Thanks for the tips. It must be both the card and the driver then.

Testing with [How was your walk?](http://erethedaybreak.deviantart.com/art/How-was-your-walk-574168962) ([flame gist](https://gist.github.com/gambhiro/df311d44b692711c8c61)).

It has 4 xforms. Scale is at 798. Windows docked only on the left side. Right and bottom scrollbars are visible.

Status bar says:

```
CPU, SP | Iters: 20,736,002. Scaled quality: 10. Total time: 1.00s.
CL,  SP | Iters: 20,742,144. Scaled quality: 10. Total time: 25.61s.
```

Dragging handles around with CL lags quite a bit. With CPU, the preview mostly disappears and only a handful "preview dots" are visible (probably due to the scale?), but the feedback is fast.

![fractorium_063](https://cloud.githubusercontent.com/assets/1586232/11903627/92895bee-a5b2-11e5-9aa3-ab74f5f62ae1.png)

![fractorium_065](https://cloud.githubusercontent.com/assets/1586232/11903626/92862d5c-a5b2-11e5-9940-607d916a346c.png)

**Comment by mfeemster** [comment]
Please try a final render using each mode with a quality of 200 and tell me what the iters/sec are reported as.

The preview dots are intentional as only one sub-batch is ran per mouse movement. Once the mouse stops, it renders the rest until the desired quality is achieved.

**Comment by gambhiro** [comment]
Interestingly enough OpenCL doesn't finish the final render.

CPU:

```
Pure render time: 9.61s
Total time: 9.61s
Total iters: 414,720,000
Iters/second: 52,589,398

All renders completed in: 9.62s.
```

OpenCL:

```
Rendering failed.

MakeAndGetFinalAccumProgram

RunFinalAccum

All renders completed in: 59.76s.
```

**Comment by gambhiro** [comment]
Thanks for the review, I have to leave now until Sunday.

**Comment by mfeemster** [comment]
Try setting the DE Max Filter Radius to 0 (disabling it).

If that works, see if you can get away with a value of 9 or less. Anything greater than 9 usually doesn't look good and can make it unstable on Nvidia cards. I spent months debugging it.

**Comment by gambhiro** [comment]
Thanks for the above tips, I think we fleshed it out properly now.

DE Max 0 and 2 works, but 5 fails.

DE Max 2:

```
Pure render time: 51.99s
Total time: 51.99s
Total iters: 414,744,576
Iters/second: 9,073,983

All renders completed in: 52.00s.
```

**Comment by mfeemster** [comment]
Glad you got it working, but there is still something severely wrong. The iters/sec you're getting with those params are well below what I'm getting on my 6 year old CPU with 4 threads. Can you test this on Windows with the same card and post the iters/sec? That will help troubleshoot whether it's a card problem, or a linux driver problem. I strongly suspect the latter. Here are some benchmark results I get with my AMD R9 280X (2048 cores), and optionally paired with Nvidia GTX 460 (384 cores). I appears that with the most basic setting of single precision and supersample of 1, the Nvidia card contributes about 300M iters/sec. So you should be seeing something around that number.

CPU AMD DOUBLE Q500 SS1
Pure render time: 38.33s
Total time: 38.33s
Total iters: 1,036,800,000
Iters/second: 27,274,162

CL AMD SINGLE Q500 SS1
Pure render time: 2.41s
Total time: 2.47s
Total iters: 1,036,812,288
Iters/second: 2,094,570,278

CL AMD SINGLE Q500 SS2
Pure render time: 2.09s
Total time: 2.28s
Total iters: 1,036,812,288
Iters/second: 2,103,067,521

CL AMD DOUBLE Q500 SS1
Pure render time: 3.49s
Total time: 3.49s
Total iters: 1,036,812,288
Iters/second: 693,519,925

CL AMD DOUBLE Q500 SS2
Pure render time: 3.10s
Total time: 3.24s
Total iters: 1,036,812,288
Iters/second: 690,287,808

CL AMD+NVIDIA SINGLE Q2000 SS1
Pure render time: 2.95s
Total time: 2.95s
Total iters: 4,152,360,960
Iters/second: 2,404,378,089

CL AMD+NVIDIA SINGLE Q2000 SS2
Pure render time: 3.61s
Total time: 3.79s
Total iters: 4,152,360,960
Iters/second: 2,071,002,972

CL AMD+NVIDIA DOUBLE Q2000 SS1
Pure render time: 8.28s
Total time: 8.38s
Total iters: 4,152,360,960
Iters/second: 805,345,415

CL AMD+NVIDIA DOUBLE Q2000 SS2
Pure render time: 6.99s
Total time: 7.05s
Total iters: 4,152,360,960
Iters/second: 777,595,685

**Comment by gambhiro** [comment]
I updated the NVIDIA driver on Windows and did some testing.

```
Driver version: 354.56
```

When I opened Fractorium, the CL button was available. Tried a few random flames. They rendered (in the preview window), but the preview feedback was lagging around a second or more. The CPU worked, feedback was fast.

When I opened [How was your walk](https://gist.github.com/gambhiro/df311d44b692711c8c61). CL rendered the preview, but when clicking in the preview window to drag a handle, it crashed with this error:

![kernel-exc](https://cloud.githubusercontent.com/assets/1586232/11977289/44ed18f6-a979-11e5-82b4-1b45f8e521a1.png)

It says it's from GL. Perhaps something with the Qt elements? Manipulating DE Max didn't solve it.

Then I used this random flame to do complete renders:

```
<flames>
<flame version="EMBER-WIN-0.9.9.2" time="0" name="Flame_2015-12-23-101556_6" size="1531 979" center="0 0" scale="240" rotate="0" supersample="2" filter="1" filter_shape="gaussian" temporal_filter_type="box" temporal_filter_width="1" quality="1000" temporal_samples="100" sub_batch_size="10240" fuse="15" background="0 0 0" brightness="4" gamma="4" highlight_power="-1" vibrancy="1" estimator_radius="0" estimator_minimum="0" estimator_curve="0.4" gamma_threshold="0.1" cam_zpos="0" cam_persp="0" cam_yaw="0" cam_pitch="0" cam_dof="0" palette_mode="step" interpolation="linear" interpolation_type="linear" plugins="stripes linear" new_linear="1" curves="0 0 1 0 0 1 1 1 1 1 1 1 0 0 1 0 0 1 1 1 1 1 1 1 0 0 1 0 0 1 1 1 1 1 1 1 0 0 1 0 0 1 1 1 1 1 1 1 ">
   <xform weight="0.2" color="0.697647" var_color="1" color_speed="0.5" name="" animate="1" stripes="1" stripes_space="0.5" stripes_warp="0.964169" coefs="0.401193 -0.302461 -0.683887 -0.127702 -0.953418 -0.123023" opacity="1"/>
   <xform weight="0.2" color="0.0864516" var_color="1" color_speed="0.5" name="" animate="1" stripes="1" stripes_space="0.5" stripes_warp="3.84586" coefs="-0.351959 -0.651258 -0.61393 -0.821641 0.710995 0.721881" opacity="1"/>
   <xform weight="0.2" color="0.931977" var_color="1" color_speed="0.5" name="" animate="1" stripes="1" stripes_space="0.5" stripes_warp="0.0313891" coefs="-0.94078 0.908784 -0.990533 -0.139216 -0.468213 0.89719" opacity="1"/>
   <xform weight="0.2" color="0.543681" var_color="1" color_speed="0.5" name="" animate="1" stripes="1" stripes_space="0.621901" stripes_warp="4.38348" coefs="-0.760226 -0.418128 0.399284 0.0572405 -0.794542 0.0488925" opacity="1"/>
   <xform weight="0.2" color="0.570118" var_color="1" color_speed="0.5" name="" animate="1" stripes="1" stripes_space="0.5" stripes_warp="3.19264" coefs="0.21236 0.996863 0.652814 0.0945474 0.500237 -0.865945" opacity="1"/>
   <xform weight="1" color="0" var_color="1" color_speed="0" name="" animate="0" linear="1" coefs="-1 0 0 -1 0 0" opacity="1"/>
   <xform weight="1" color="1" var_color="1" color_speed="0" name="" animate="0" linear="1" coefs="-1 0 0 1 0 0" opacity="1"/>
   <palette count="256" format="RGB">
      70232d550828631e2171351b7635227b35298f3b2ea34134
      aa097b7c0e744f146e371d691f2765161f600d175c231c4e
      39214178648773828b6ea1907abea586dbba85e3b885ecb7
      60d69c6ace8574c76f6c9854646a3a52592a40491a213615
      0e2d250216530717490d193f0d1d330e21270f2025101f24
      2530225125197d1b108c1e0b9b22079f2503a328009b3b08
      6d3c1c21250c211a07210f03100b0700070c000406000100
      15030f2009092b0f03321715391f283c2e373f3e464e6b4f
      526e482e6217335c143857112a581b1d5925104a21134427
      31380f3d311b492a2755504162765b64956567b47066e981
      59d57336945f21695f0d3e5f062660000e6111083f23112b
      2c212524262d1d2b3620253f241f48211e49123a460f5b3d
      205636255e292a4c292f3a293338283836273d25336c2c2a
      91173e800f286f07125412133a1d15122021022f18063515
      0750230e6727116120155c1a246a112d710c287c2442785e
      4398954286744174534573564a725a68856982955eb1b64f
      ccc56af6e29bead477dec753e49c48f65d4bb58851988f4e
      b98c6baf9978a5a686aab088afbb8badbc8194b66275ae81
      579a89277c5f187a670a786f0b69570661360f871b19810e
      0f43030f3e0c103a160e2a2e162e32331b3f46065a47184e
      342d5639571b5270196b8917a79e1be5af1bffc421eca235
      707e2f657c2b5b7b286462326a593f3d48375e5131724319
      6a3b21512026452d214d6831698c3085a13ba2b84ccacc2b
      ef8f21ce8327ad772daf5b39a9203cd10930d4050bc51321
      b916197d08224e09264c0b43741768641c724c147f334367
      254b5e204f49307731546c30616c106d5f14715202592c03
      501d083710091f0a1b0905160b08190b14250d1c230c0c14
      19170b181b123a361060571c9572388d943577815c7a9f5c
      73986c71a26b6da389aa7db69e777a936a7a846970774f71
      7165553c6d4d117269164c7811455a0a444f115150214c3b
      3c4530623f197a671b90751a9d852fab6d3ce55d4fde5159
      b5566cbd326bcb1077d31650d24f3baf61176c7613218022
   </palette>
   <edit date="Wed Dec 23 10:16:46 GMT Standard Time 2015" action="edit">
      <edit filename="" index="5"/>
   </edit>
</flame>
</flames>
```

This I could render. I set DE Max to 2. I think it was not double precision.

```
CL, NVIDIA, Q200
Pure render time: 18.01s
Total time: 18.01s
Total iters: 299,794,432
Iters/second: 23,933,772

CPU, Q200
Pure render time: 6.39s
Total time: 6.41s
Total iters: 299,769,800
Iters/second: 52,888,108
```

When I exited the program, it gave another error though:

![exit-error](https://cloud.githubusercontent.com/assets/1586232/11977287/44e4a52c-a979-11e5-86ff-742242dde0bd.png)

Nvidia driver reports:

![nvidia-driver](https://cloud.githubusercontent.com/assets/1586232/11977288/44ea7b6e-a979-11e5-9e51-b4d802bd4113.png)

**Comment by gambhiro** [comment]
It occurs to me that [How was your walk](https://gist.github.com/gambhiro/df311d44b692711c8c61) uses Xaos, which the random flames I think don't. Perhaps that influences something.

**Comment by mfeemster** [comment]
This is unfortunate, because according to the specs, that card should work fine. My Nvidia card is almost identical.

Have you opened the options dialog and are you sure you are selecting the Nvidia card?

The pure virtual function call error on shutdown is one that many have reported, but I have been unable to reproduce. I think it has something to do with the Intel OpenCL drivers being present on the machine.

It does indeed do some things a little differently with xaos, but nothing that would cause any problems.

There is not much I can do on this issue. I could possibly provide you with a private debug build. It will run extremely slowly, but might provide more info on a crash.

If you or anyone else can build and debug it, that's the only way to truly solve it. Otherwise, we'll just have to say your card doesn't work.

**Comment by gambhiro** [comment]
It doesn't worry me, the CPU mode is already such an upgrade from Apo.

**Comment by mfeemster** [comment]
I am sorry to hear that we can't fix it,. You haven't lived until you've fractaled on a GPU =)

If you can find another Windows machine with a good GPU to run it on, give it a try. You'll see what I mean.
