### ISSUE TITLE
User guide and hardware stats on startup

### ISSUE THREAD

**Issue by gambhiro** [mfeemster/fractorium#44]
I would like to suggest to display a user guide on startup, with the usual "don't show this on startup" checkbox, and the guide being available from the Help menu.

One part of it could be an interface walk-through. Text with screenshots.

But at that point a more complicated feature can be introduced. The user has just opened the application for the first time, and Fractorium can ask permission from the user to collect hardware stats, submits that to an online database, and then displays some green / red / etc. rating about how well his card and CPU might be expected to perform.

What do you think?

It is very well that we discussed a particular card in #42, but when the average user experiences an issue like that, they will just feel frustrated, confused, and abandon the application.

Even if we collected a list of "well working" and "not well working" cards on a wiki page, it is still too much to expect from the user to investigate what exact card they have and then go to something as technical as a github wiki page to look up its performance rating.

**Comment by gambhiro** [comment]
I can write a simple online app with an API where Fractorium can submit to. For hosting, a free Heroku node would do.

**Comment by gambhiro** [comment]
Or perhaps it is enough to match some general properties about the hardware? And then an app and online DB is overkill.

**Comment by mfeemster** [comment]
The DB is overkill, and in general this is far beyond the scope of what I'll be doing in this project. Others are welcome to implement it if they'd like and submit a PR, so I'll leave this open. It would likely be two to three months worth of work.

There is already code to investigate some basic properties of the card, OpenCL makes it easy to do that. The command line programs can report it with the --openclinfo argument. It would be a matter of somehow doing that within Fractorium and reporting it.

As a general rule, it requires Fermi or later card for Nvidia, and GCN card for AMD.

But as far as larger documentation, I've stated on DA that I intend to make a website. The github wiki has alway been intended as a stopgap until I get time to make a legitimate website. I've always had to choose between implementing desperately needed features/bug fixes and making a site. The former always got priority.

After I make an official non-beta 1.0 release, I will be transitioning to the website/documentation portion of things and doing very little work in the code.

**Comment by gambhiro** [comment]
@mfeemster yes, complete overkill. Thanks for the reply. No need to pollute the open issue list with this.
