### ISSUE TITLE
preview quality settings

### ISSUE THREAD

**Issue by gambhiro** [mfeemster/fractorium#46]
Would it be possible to have some settings to influence the quality of the preview? I.e. when dragging around handles.

Chaotica for example has a "more dense" preview, and this helps a lot in the exploring stage, looking for features in a combo, or tweaking positions to align details.

The current preview is not very dense, and gets completely lost when you scale the flame.

**Comment by mfeemster** [comment]
You can already do this, but it will slow things down when dragging. See the options dialog.

https://github.com/mfeemster/fractorium/wiki/Options-Dialog#CPU_Sub_Batch

Always check the wiki first =)
