### ISSUE TITLE
Getting Fractorium to run on Ubuntu 14.04 derived distros is as easy as roasting snowballs crispy

### ISSUE THREAD

**Issue by MAD-OVERLORD** [mfeemster/fractorium#51]
Hello, first a big fat virtual ass kiss, that you made and share a GPU flame render in C/C++ which i more or less luckily discovered some hours ago, as i was reporting some bugs/problems on CUBURNs github page, which had tortured me well some days before your FRACTORIUM :).
Sadly i couldn't get FRACTORIUM to work after several hours on a LTS Mint17+Ubuntu Studios 14.04.

The PPA which is only for 15.04 Distros as i found out after adding(maybe you should mention that, since linux users with even minimal install discipline have a lot of paranoid thoughts going on in their lill' brains before adding a PPA and they have to enter sudo passwords which are longer and more random then the crap that stands in the bible), of course did nothing.
Then the .dep file did a bit more nothing, because of stupid dependencies..
Simply injecting the content of fractorium_0.9.9.3b-0ubuntu1_amd64.deb in my system what i usually do, since dependencies are often grabbed out of thin air, did even more nothing...
Yup, behold i really have to compile, so i loaded the shotgun and played some good old nirvana songs to come in the mood and be prepared for the worst.....
The problem is, FRACTORIUM didn't want to install nor to be compiled because ubnutus repository is seriously fucked up, since they install gcc-4.9.3-base(what can't be removed) but don't provide any matching libstdc++ 4.9, only 4.8, what in turn is not sufficient for the demanded libqt5core5a v5.4, which i found on launchpad somewhere.

By stalking around a bit,
https://forum.qt.io/topic/49218/qscrollarea-with-qglwidget-on-linux-is-completely-broken
i found out, that you are also on Mint17 X64, so could you please tell me how it should be possible to install FRACTORIUM on that crap system?

Thanks a lot and have a nice time

**Comment by gambhiro** [comment]
So, if I'm reading this right, you are saying that, on Mint 17, trying to install from the PPA or the .deb failed, because they didn't find the dependencies in the Mint repositories? It is entirely possible. I tested on Ubuntu 15.10. What deps did it fail on?

Compiling from Github should be better though. Does the [BuildGuideLinux.md](https://github.com/mfeemster/fractorium/blob/master/Data/BuildGuideLinux.md) help? If not, is it missing deps again, or something else?

**Comment by mfeemster** [comment]
@MAD-OVERLORD Glad you found this project. You'll be happy to know I got the core of the GPU rendering code from cuburn and actually exchanged many emails with Steve Robertson. However, his animation portion is much more advanced. In the future, it would be wise to scrap most of what flam3 did with animation and re-implement what cuburn did in C++.

Anyway, I only write the code and do basic validation on Linux. @gambhiro handles making the package. It's up to him whether he wants to make one for Ubuntu 14.04.

Final note: I hadn't checked his page in years, thanks for reminding me about it. It appears he has done some work recently. I know he took a break for a long time.

**Comment by MAD-OVERLORD** [comment]
@gambhiro 
Your PPA said, that i am a dumb monkey from outer space or something like that...
W: Fehlschlag beim Holen von http://ppa.launchpad.net/fractorium/ppa/ubuntu/dists/trusty/main/source/Sources  404  Not Found
W: Fehlschlag beim Holen von http://ppa.launchpad.net/fractorium/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
W: Fehlschlag beim Holen von http://ppa.launchpad.net/fractorium/ppa/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found
What probably lies in the fact that you have no data for 14.04 trusty ubuntus, or that i should configure my system to also fetch from 15.04/15.10.

Gdebi said Ian was killed by cops, game over, go to arch linux
gdebi fractorium_0.9.9.3b-0ubuntu1_amd64.deb
Dependency is not satisfiable: libqt5core5a (>= 5.4.0)

But in ubuntu 14.04 we only have 5.2.1+dfsg-1ubuntu14.3 as the highest version, so i tried to install from
https://launchpad.net/ubuntu/vivid/amd64/libqt5core5a/5.4.1+dfsg-2ubuntu4
Then gdebi only replayed "Don't you understand, Ian is death and Mr. Shuttleworth is even more gay than capitalism"
gdebi libqt5core5a_5.4.1+dfsg-2ubuntu4_amd64.deb
Dependency is not satisfiable: libstdc++6 (>= 4.9)

Synaptic then said 4.8.4-2ubuntu1~14.04 is all you will get from me, so i again searched outside synaptic @ 
https://launchpad.net/ubuntu/wily/amd64/libstdc++-4.9-dev/4.9.3-5ubuntu1
since it was the only thing i could find with libstdc++
gdebi libstdc++-4.9-dev_4.9.3-5ubuntu1_amd64.deb
Dependency is not satisfiable: gcc-4.9-base (= 4.9.3-5ubuntu1)

Since i couldn't bring it on par with that gcc, i wanted to remove gcc-4.9-base 4.9.3-0ubuntu4 because i found 2 matching ones, but that wasn't possible, because synaptic then wanted to fuck my whole system by removing everything.........
Personal side note, rescue your ass to slackware or DSL or where ever they hopefully not have any package management at all...


Of course i have followed BuildGuideLinux.md, guess what, even from start to finish and not the other way round, but if the distro fucks you where it can, this helps not that much, and to be honest, if you want to look at least a little bit professional, you should build for LTS versions and not "vapor ware" like 15.04 or generally everything in between "Long Time Service" versions, i think such a good project really deserves it!

Here the important part of the compile attempt 
.obj/fractorium.gch/c++
../../../Source/Fractorium/FractoriumPch.h:50:25: fatal error: QOpenGLWidget: Datei oder Verzeichnis nicht gefunden
 #include <QOpenGLWidget>
                         ^
compilation terminated.
make[1]: *** [../.obj/fractorium.gch/c++] Fehler 1
make[1]: Verzeichnis »/tmp/fractorium/Builds/QtCreator/Fractorium« wird verlassen
make: *** [sub-Builds-QtCreator-Fractorium-make_first-ordered] Fehler 2


Have fun :)

**Comment by MAD-OVERLORD** [comment]
@mfeemster 
Wow, the chief commander him self spoke, what a great reaction time compared to cuburn :D
Ahm, yeah, that mystical animation system of cuburn no one ever used because it is even for linux consoleros a strange thing and as he himself has stated, probably vapor ware without a GUI, sad story, i hope yours will not end this way.
It is really fantastic, that you made it in C++, it is somehow the only language besides C and bash that my brain wants to interpret, if something is in python or java i got a strong urge to run away.

As i wrote in the initial comment, i already stalked what i could and saw that you do your so called basic validation on the same system(Mint17 X64) on which i could by the best will and several hours, not "validate", that FRACTORIUM runs or compiles nor anything else, so how did you get this crappy mint to have all the dependencies? 

He really should build for 14.04 because it is the last LTS (Long Term Service) version, the most people stick with such versions, because they are the only ones which are relatively "stable" and what you build for them, doesn't get void so fast and maybe it lasts even for the 5 years they "support" and if he had done a 14.04 build it would be probably more compatible with newer versions than the other way round, what we face now!

Final note:
Since i have read in your interview at deviantart, that you have some 3D plans in mind, or maybe in general, it could be of interest what was exchanged here:
https://github.com/stevenrobertson/cuburn/issues/10
(By the way, till now, i didn't observed that desktop freezing i always get with CUDA apps, and your emberrender is slightly faster then cuburn)

Thanks a lot for your hard work and i wish you all the best

**Comment by mfeemster** [comment]
@MAD-OVERLORD Thanks for the kind words.

That's funny you found that old Qt post of mine, just one of many frustrating quirks I had to work through.

Building on Linux Mint took me a little while. I know this is not the proper place to put these instructions, but see the comments in this post:

http://mfeemster.deviantart.com/journal/Fractorium-Beta-0-9-9-0-Released-561330048

I detail what I had to do to get it to build. Notice I built Qt from scratch. I'm not sure if that's still required though. It worked for me and seemed to work for Mick as well.

I will put those notes in another place when I get some time, which should be in the next 2 to 3 months.

You make a reasonable case for making a package for 14.04 LTS. It's up to @gambhiro whether he wants to spend his next few weekends making it work =)

As for the 3D, that's a long, long way off, if ever.

I really hope you are able to get this working, sorry for all the troubles.

**Comment by MAD-OVERLORD** [comment]
I also found other stuff, like that you are a lill' evil genius in weapon systems, is that really true, that those stuff runs on windoze? 
If so, i hope at least the atomic arsenal does not :S
By the way, is that not a bit schizophrenic to search for the holy grail (Ayahuasca)(have you ridden the snakes and crocodiles already?0.o), then programing humanity's most beautiful art tool, just as a hobby besides working all day long for the most dark and evil thing humanity ever created?
Don't get me wrong, i am not judging you for that, clearly overpopulation is the biggest thread of all, but have you guys ever thought about the problem, that when everybody knows about weapons like metalstorm and the like, people on both side of the coin will one day loose their naive sight of "war is something heroic and i get lots of bitches when i don't return as a heroin drowned cripple", because it obviously gets more of a "hey stupid negro/latino kid, lets jump in the meat grinder man" thing, that even the most stupid ones realize?
Couldn't you come up with something more creative, like building 24/7/365 "burning man" concentration camps, where we all voluntarily run to, to drug the shit out of us day and night till we all die happy? ;) 

Sorry, that was a bit off topic, where was i, ahh yes, linux instructions hidden at deviantart, that was so brilliant, not even google found it, guess i hide my secret world domination plans there from the NSA next time :D

As long as you would mention it on your github page where you put that knowledge, there is no acute need for cosmetics.

You mean, that those interactive GLSL realtime mandelbulb spacetown journeys this freak here has done, is even more complex than flames?
http://glslsandbox.com/e#28950.0

No need to feel sorry, if you had to choose such a high version of QT because of some features, that's the distros fault not providing us with those QT versions, but if you see a way to downgrade your really needed QT version, then, when it is in your interest to be really multi plattform, i suggest that you always stick with the possibilities of the "weakest" OS in your chain, because your "it's his fault @SomePoorPackager" who had to live with your basic decisions and then had to do some wonders in packaging for linux or even breaking peoples systems by not knowing what he does, is not always a winning philosophy ;)

Thanks for your time and the great work, i wish you a nice evening or whatever you have there right now.

**Comment by mfeemster** [comment]
No comment on the first few paragraphs, for obvious reasons =)

I do need to use Qt 5.4, for reasons discussed in the post of mine you found. It fixes various bugs found in older versions. So there's nothing that can be done there.

We'll do our best to keep the install and build process as painless as possible. I'm going to close out this issue now.

**Comment by MAD-OVERLORD** [comment]
Ok, do as you wish, i maybe post in some days how the deviant infos about first compiling Qt fruited or not.

=D I guess i made your day with that. Don't forget to suggest my neat idea to your boss next week, it is really time for a real change in the ancient overpopulation management =D

**Comment by JrSchild** [comment]
Okay I probably shouldn't get involved. But thank you @MAD-OVERLORD for the great amusement today :'D

**Comment by MAD-OVERLORD** [comment]
@JrSchild 
The question is moreover why you should not be involved? That's no war here or something the like, at least not for me, i call it philosophical bug reporting and in such a team sport you should always get involved as this old piece of net culture correctly manifests:
https://youtu.be/nr8jqQcR8TA
(Time link/anchor doesn't work with activated script blockers, so goto 5:30)
What amusement? I am totally sirius man :D
