### ISSUE TITLE
Any Xform that has the boarders variation leads to false renderings, those with wedge_sph sometimes too

### ISSUE THREAD

**Issue by MAD-OVERLORD** [mfeemster/fractorium#53]
I believe i have seen this little problem already posted somewhere, but here i didn't found it, not even in the closed ones, so i post it again.
On the over 1000 flames i had test rendered, almost any one with that boarders variation showed some anomalies, so i guess it could be reproduced easily.
If not, try this one, it was the most horrible anomaly in my gallery
[boarders-test.flam3.zip](https://github.com/mfeemster/fractorium/files/106909/boarders-test.flam3.zip)

PS.
 If it should matter, i generated them with Qosmic and rendered them with:
emberrender --opencl --earlyclip --flam3_palettes="/usr/share/fractorium/flam3-palettes.xml" --bits=33 --qs=1.0 --ss=1.0 --in="XXX.flam3" --format=png --bpc=8 --out="YYY.png"

PS.2 
I think i don't have to open a separate issue for that one, since i believe i have only a small couple of renderings with it, but if someone is interested, the wedge_sph variation also renders completely something else, then what i see/render in Qosmic(Sadly still didn't got the time to get Fractorium to work)
[Wedge_sph.flam3.zip](https://github.com/mfeemster/fractorium/files/106989/Wedge_sph.flam3.zip)

PS.3
Beside of these lill' problems i really have to congratulate you, since emberrender had not one of the problems which i had to post on the probably lost cuburn project, that was a really amazing finding :) 
https://github.com/stevenrobertson/cuburn/issues

**Comment by mfeemster** [comment]
Good catch, boarders and wedge_sph did indeed have bugs in them. I've fixed them and they'll be available in the next release.

**Comment by MAD-OVERLORD** [comment]
@mfeemster 
Ooops, i basically just wanted to cancel a comment i started, but by the way, should i close this now since you fixed it, or should i wait till i have tested the new version?
(I am not so familiar with "multiplay" stuff like github, therefore sorry for the noobish questions sometimes)

**Comment by mfeemster** [comment]
I've committed the fix, so if you update your source, you should be able to build and test this. Close it once you've verified those variations come out correct.

**Comment by MAD-OVERLORD** [comment]
@mfeemster 
Congratulations, even if i hadn't the time to test them all, the most important ones seem to be OK now, you really do a great job on your project here, that was a gigantic GPU test over 1000 different, mostly random created flames, with many different variations, so a really hard test and as far as i can see, emberrender rendered them all very nice :)
