### ISSUE TITLE
Several severe problems on rendering 1000s of different flames with emberrender on GPU

### ISSUE THREAD

**Issue by MAD-OVERLORD** [mfeemster/fractorium#54]
Before you get a headache from my observations down there, what i suggest to solve these problems is:
1) In my tests quality=500,estimator=3 was almost the maximum we could use with --opencl @720p, so we really need params like: --quality-override=\<val>   --estimator-override=\<val>   and maybe --passes-override=\<val> like you made with --supersample=\<val> to be able to handle big batches of flames which may have quality=2000 estimator=11 set, like electricsheeps usually do(Your --qs=\<val> would of course be sufficient if all flames had the same quality, but in case of my gallery and other stuff from the web, where we had qualities ranging from 5-4000 mixed all together, i believe my suggestion would be supperior)

2) Even if we had corrected these values, there are still some sorts of variations or whatever, which lead to quiet longer render times, then we would have on CPU, so i suggest to make some sort of rendertime threshold parameter like:
--gpu-rendertime-treshold-and-handling=\<val> \<command>
so that we could choose what will happen when it renders too long, like 
exit666
or 
echo "$@ was too slow with EMBERRENDER IN GPU MODE" >> "/tmp/Log.log" && flam3-render < "$@" 
or whatever someone want to do then, instead that you just internally switch over to CPU mode, or as it is till now, that you just skip over to the next one.
(Of course one could just do that in a bash script, but it has somehow a damn long reaction time by killing it off externally, so i thought, maybe it goes faster and more secure if you stop it internally)

3) Not related to the problems, but since i am making suggestions here, i also wanted to suggest, that it would be better to have PNG as default, at least for emberrender, where we are more focused on quality, but i also observed better quality videos made out of PNGs then the ones which were made out of JPEGs, so the usual answer "The video compression codec cripples it anyway to a blurry shit" is not that true, since shit*shit is usually more shitty, so this could therefore also apply to emberanimate. BTW, i noticed, that the renderings in PNG from emberrender --opencl --earlyclip are always not so intense as the ones from Qosmic/Flam3-Render with earlyclip were, now i am asking myself, is that because we can only use 8bpc with --opencl or is it the earlyclip that maybe works different. I also noticed, that renderings in PNG from Qosmic at the same dimensions, are always 2.8mb, while renderings from emberrender are mostly <1mb, so since you only provide parameters for the jpeg quality, i could also imagine, that this small quality loss comes from some hardcoded PNG compression level(If so, please provide a PNG quality parameter as well)

Whilst emberanimate may reach an reasonable speed boost with --opencl on a particular well configured/optimized flame when rendering some series of it as an animation, emberrender on 1000s of different flames, with different non optimized configurations, had quiet a bit longer to render those 1000 flames and not to mention, before it even rendered them, it crapped out on many and some did render for over 7minutes on a flame, which i had rendered with flam3-render in a couple of seconds.
That was on my own flame gallery, which is more focused on simple eye appealing art, compared to the totally overblown alien abduction electricsheeps usually are, so there were not 100Xforms or to complicated stuff going on.
With electricsheeps, things are even worse, most of them i had tested, crapped out at rendering, here are some examples of these miraculous alien abductions which won't render at all:
[Flames-from-the-electricsheep-website.zip](https://github.com/mfeemster/fractorium/files/107143/Flames-from-the-electricsheep-website.zip)
Stage = filtering, progress = 100%, eta = 0.00sError: image rendering failed, skipping to next image.
MakeAndGetFinalAccumProgram
RunFinalAccum

And that was on a not so bad gaming machine:
OpenCL Info: 
Platform 0: NVIDIA Corporation NVIDIA CUDA OpenCL 1.2 CUDA 7.5.23
Device 0: NVIDIA Corporation GeForce GTX 870M
CL_DEVICE_OPENCL_C_VERSION: OpenCL C 1.2 
CL_DEVICE_LOCAL_MEM_SIZE: 49'152
CL_DEVICE_LOCAL_MEM_TYPE: 1
CL_DEVICE_MAX_COMPUTE_UNITS: 7
CL_DEVICE_MAX_READ_IMAGE_ARGS: 256
CL_DEVICE_MAX_WRITE_IMAGE_ARGS: 16
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 805'257'216
CL_DEVICE_ADDRESS_BITS: 64
CL_DEVICE_GLOBAL_MEM_CACHE_TYPE: 2
CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE: 128
CL_DEVICE_GLOBAL_MEM_CACHE_SIZE: 114'688
CL_DEVICE_GLOBAL_MEM_SIZE: 3'221'028'864
CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE: 65'536
CL_DEVICE_MAX_CONSTANT_ARGS: 9
CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS: 3
CL_DEVICE_MAX_WORK_GROUP_SIZE: 1'024
CL_DEVICE_MAX_WORK_ITEM_SIZES: 1'024, 1'024, 64

while true; do date; nvidia-smi -a | grep -i Used; sleep 1; done >> /tmp/Nvidia.log
showed me, that even if my whole desktop freezes terribly on rendering these electric sheep, that it is only a matter on the graphical side, the rest works fine and shows also, that never during the rendering till the "crash" and after, there was more GPU ram consumption then 400mb of the 3gb, so that is not the problem.

Probably i forgot the most things i have tested, but i believe it boils down to the things i suggested in point 1. and point 2.

Is it well known which variations are not that optimal for GPU rendering or should we create some sort of knowledge database about these, so that emberrender one day will be able to directly switch over to CPU if it sees problematic variations in the flam3 header?

Probably off topic: The heavy desktop freezes i thought were better with emberrenders opencl then with cuburns CUDA, just didn't appear in my first tests, because i rendered in low resolutions or easy flames, but when i render electricsheeps, my desktop stays even frozen for 20secs sometimes. I also observed, that when i try to load a picture when the lags begin, it loads that picture line by line, so i guess for some reasons, opencl and CUDA eaten up my whole graphics power, what i don't really understand, since when i run ./query or what it was called to show CUDA informations it clearly said, that i have dedicated cuda cores and not shared ones, so does any one perhaps know, why to hell that happens and where the problem lies, how we can trace this down and how we can find a solution for this problem?

**Comment by mfeemster** [comment]
Can you please break each of these into a separate issue and I will address them one at a time. It's too easy to get lost going back and forth with so many items in one issue. Thanks.

**Comment by MAD-OVERLORD** [comment]
@mfeemster 
Sorry man, since it was almost one investigation for me, i thought i make one post, but you are completely right, it was a little bitty too much in one piece for mere mortals =D
I broke it all up to tiny pieces now, at least i hope sufficiently tiny, because more wouldn't be possible without losing context, at least for how i saw the context.
Thanks in advance for adding some of the important features i mentioned in these.
