### ISSUE TITLE
Besides the quality and estimator value, there seem to be some variations which slows the GPU rendering down

### ISSUE THREAD

**Issue by MAD-OVERLORD** [mfeemster/fractorium#56]
2) Even if we had lowered these quality and estimator values, there are still some sorts of variations or whatever, which lead to quiet longer render times, then we would have on CPU, so i suggest to make some sort of GPU rendertime threshold parameter like:
--gpu-rendertime-threshold-and-handling=\<val> \<command>
so that we could choose what will happen when it renders too long, like 
exit 666 (\# I know, exit status value shouldn't exceed 255, but i guess Mark Kilgard left his mark on me :S)
or 
echo "$@ was too slow with EMBERRENDER IN GPU MODE" >> "/tmp/Log.log"; flam3-render < "$@" 
or whatever someone want to do then, instead that you just internally switch over to CPU mode, or as it is till now, that you just skip over to the next one.
(Of course one could just do that in a bash script, but it has somehow a damn long reaction time by killing it off externally, so i thought, maybe it goes faster and more secure if you stop it internally after given threshold)

Is it well known which variations are not that optimal for GPU rendering or should we create some sort of knowledge database about these, so that emberrender one day will be able to directly switch over to CPU if it sees problematic variations in the flam3 header?

**Comment by mfeemster** [comment]
I am not going to implement this. Please provide the Xmls for the flames that took longer and I can give them a closer look.

There are some that take longer. There is a way of programmatically getting this information and I've experimented with it in the past. It's something I can include once I make a website.

**Comment by MAD-OVERLORD** [comment]
@mfeemster 
I am not that sure right now, but i think what i have seen in the tests, was that supersamples over 1 lead to much longer render times then on CPU, what i just found out recently and you knew that probably already much longer, that you had this --supersample override param already.
I think with the knowledge over these 3 problem factors quality+demax+supersample we get indeed GPU renderings that are a bit faster then CPU, so i close this now in hope that i don't have to resurrect it after my new big test over 1000 flames in the next days.
