### ISSUE TITLE
I have extreme desktop freezes for as long, as eberrender renders in GPU mode

### ISSUE THREAD

**Issue by MAD-OVERLORD** [mfeemster/fractorium#57]
The heavy desktop freezes i thought were better with emberrenders opencl then with cuburns CUDA, just didn't appear in my first tests(which i mentioned here somewhere in a comment), because i rendered in low resolutions or easy flames, but when i render electricsheeps, my desktop stays even frozen for 20secs sometimes per flame, alias probably the whole rendertime. I also observed, that when i try to load a picture when the lags begin, it loads that picture line by line, so i guess for some reasons, opencl and CUDA eaten up my whole graphics power, what i don't really understand, since when i run ./query or what it was called to show CUDA informations it clearly said, that i have dedicated cuda cores and not shared ones, so does any one perhaps know, why to hell that happens and where the problem lies, how we can trace this down and how we can find a solution for this problem?

And that was on a not so bad gaming machine:
OpenCL Info: 
Platform 0: NVIDIA Corporation NVIDIA CUDA OpenCL 1.2 CUDA 7.5.23
Device 0: NVIDIA Corporation GeForce GTX 870M
CL_DEVICE_OPENCL_C_VERSION: OpenCL C 1.2 
CL_DEVICE_LOCAL_MEM_SIZE: 49'152
CL_DEVICE_LOCAL_MEM_TYPE: 1
CL_DEVICE_MAX_COMPUTE_UNITS: 7
CL_DEVICE_MAX_READ_IMAGE_ARGS: 256
CL_DEVICE_MAX_WRITE_IMAGE_ARGS: 16
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 805'257'216
CL_DEVICE_ADDRESS_BITS: 64
CL_DEVICE_GLOBAL_MEM_CACHE_TYPE: 2
CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE: 128
CL_DEVICE_GLOBAL_MEM_CACHE_SIZE: 114'688
CL_DEVICE_GLOBAL_MEM_SIZE: 3'221'028'864
CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE: 65'536
CL_DEVICE_MAX_CONSTANT_ARGS: 9
CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS: 3
CL_DEVICE_MAX_WORK_GROUP_SIZE: 1'024
CL_DEVICE_MAX_WORK_ITEM_SIZES: 1'024, 1'024, 64

while true; do date; nvidia-smi -a | grep -i Used; sleep 1; done >> /tmp/Nvidia.log
showed me, that even if my whole desktop freezes terribly on rendering these electric sheep, that it is only a matter on the graphical side, the rest works fine and shows also, that never during the rendering/freezes, there was more GPU ram consumption then 400mb of the 3gb, so that is not the problem i think.

**Comment by mfeemster** [comment]
The UI freezes sound bad, but are not entirely unexpected. I definitely get a system-wide UI slowdown/freeze when doing heavy rendering on the GPU. There is no way around it because this algorithm stresses the card very hard. However, that slowdown might be worse on Linux because as a general rule, drivers are worse there. There is nothing I can do about this, although I will note it in future documentation.

**Comment by MAD-OVERLORD** [comment]
Ah, that is nice to know, and yes if you find the time, note that somewhere, it is really something that lefts one with many ??? on GPU renderings, since we wrongly believe, that we have dedicated cores and something shouldn't happen, so in the words of our great "leader" Linus >>>FUCK YOU NVIDIA!!!<<< i want back the great times with the really dedicated ageia physx cards!!!

But since we're all smart hackers, shouldn't there be a way to just throttle it a bit, like "no you stupid CUDA opencl shit, my system needs at least XXX cores to show me the life-sustaining boob pictures!" or something like that? 0.o

With AMD drivers you may be right, even the free gallium drivers are better and have more features like the accelerated video playback, which the AMD drivers didn't provide for a long time, after the free ones had it implemented already, but on the NVIDIA side it is completely different, first, the desktop icon arrangement doesn't get killed each time we update drivers on Linux(what i really hate on win7 "ultimate"), i have seen computers which were branded somehow by companies that went bankrupt, so the users couldn't update their lousy shipped graphics drivers on windoze with the NVIDIA installer, but with the newest linux NVIDIA drivers they just worked fine and out of the box, i also had once a Asus G73 gaming laptop which permanently made click of death sounds on the harddisks on windoze, which the tech support said to be coming from NVIDIA drivers(as stupid this may sound), but i had not one problem on Linux with this same machine, the cheap medion laptop gaming rig i have now, constantly overheated on the win8.1 crap they shipped and with Linux drivers the problems are less and the temperatures not so often in the 90's, except on loads the cooling system also can't keep up with and my last note is, that top title games which were natively linux compatible ever had at least 5-10 FPS more on linux, particular i mean: Unreal Tournament, Rune Halls of Valhalla, Postal 2, Aliens VS. Predator and those days i enjoy Mount and Blade Warband, Garrys MOD, War Thunder, Chivalry, Dying Light, ARK Survival and so on, much smoother and without any overheating slowdowns on Linux and the best of all is, due to EXT4 access rights management, hackers don't just hijack my system or infect my game bins, therefore NO!, there are no such general rules, that on Linux anything could be more worse then on windoze(At least if one follows the general rule, that Linux mostly works best with Intel/NVIDIA/HP) :D
