### ISSUE TITLE
Just a little suggestion about setting PNG as the standard for emberrender at least

### ISSUE THREAD

**Issue by MAD-OVERLORD** [mfeemster/fractorium#58]
3) Not related to the problems, but since i am making suggestions here, i also wanted to suggest, that it would be better to have PNG as default, at least for emberrender, where we are more focused on quality, but i also observed better quality videos made out of PNGs then the ones which were made out of JPEGs, so the usual answer "The video compression codec cripples it anyway to a blurry shit" is not that true, since shit*shit is usually more shitty, so this could therefore also apply to emberanimate.

**Comment by mfeemster** [comment]
Good catch. The default already is png, however the help text said it was jpg. Internally it was using png. The help text has been fixed in the latest commit.
