### ISSUE TITLE
Emberrender has slightly less quality on PNG renders with --opencl then Qosmic(Flam3-Render based) had

### ISSUE THREAD

**Issue by MAD-OVERLORD** [mfeemster/fractorium#59]
BTW, i noticed, that the renderings in PNG from emberrender --opencl --earlyclip are always not so intense as the ones from Qosmic/Flam3-Render with earlyclip were, now i am asking myself, is that because we can only use 8bpc with --opencl or is it the earlyclip that maybe works different. I also noticed, that renderings in PNG from Qosmic at the same dimensions, are always 2.8mb, while renderings from emberrender are mostly <1mb, so since you only provide parameters for the jpeg quality, i could also imagine, that this small quality loss comes from some hardcoded PNG compression level(If so, please provide a PNG quality parameter as well)

**Comment by mfeemster** [comment]
Earlyclip: I support earlyclip, however I don't support anything relating to Qosmic. It is a legacy program that I have nothing to do with. I am only supporting this project. If you have an image that uses earlyclip which you think is producing an incorrect output, please provide the parameters and comparison output images from Qosmic and EmberRender.

Png compression: This project uses lossless png compression. I'm not sure why the sizes of the images from other programs are different. If you see any clearly identifiable artifacts, please provide sample parameters and comparison output images from Qosmic and EmberRender.

**Comment by mfeemster** [comment]
Are you still looking into this issue? Please provide samples, otherwise I will consider it a non-issue and close it.

**Comment by MAD-OVERLORD** [comment]
I couldn't imagine, that i made such a post, if there would be no truth behind, but since i don't have the time to do two times a comparison rendering of all my over 1000 flames, because my machine is then unusably fried for hours as stated in https://github.com/mfeemster/fractorium/issues/64 and to loud to render over night, as well that i couldn't just remember, on which ones the problems existed, but as far as i can remember on some that are my most absolute treasures, which i didn't wanted to share with the world at the moment by posting them here, i guess i just close this for now.

The only thing i see now after a little test on electric sheeps is, that --earlyclip which i ever thought of to be a param, which should be used always, is maybe not a so good practice i saw on this two here, on which the one here with earlyclip has something i probably would consider a loss of its intensity.
![With earlyclip 33bit ss1 demax11](https://cloud.githubusercontent.com/assets/16815857/12969431/9e36a16a-d080-11e5-9b3c-912f479005dd.png)
For my likings i find it better, more intense without earlyclip
![cpu 23sek](https://cloud.githubusercontent.com/assets/16815857/12969474/349add06-d081-11e5-97e3-87d1193a99be.png)
Ehm, somehow i don't see much difference here on my firefox, but if i redownload them and click back and forth between these two in my picture viewer(EyeOfMate), it makes quite a difference.

**Comment by mfeemster** [comment]
You don't need to render all 1000 images. If there is a serious problem with the png output of either program, you will see it right away.

If it involves a specific image you don't want to post here, you can always email it to me privately. I never share any data with anyone.

Otherwise, we'll consider this as a non-issue since the png output of our program looks fine to me.

Regarding earlyclip (AGAIN, PLEASE KEEP EACH TICKET TO *ONE* ITEM), sometimes it makes things look better, other times worse. That's why it's kept as an option.
