### ISSUE TITLE
Xforms with the Pie Variation don't render as expected

### ISSUE THREAD

**Issue by MAD-OVERLORD** [mfeemster/fractorium#60]
It should show 3/4 of the pie.
[PieVariationBug.zip](https://github.com/mfeemster/fractorium/files/121269/PieVariationBug.zip)

**Comment by mfeemster** [comment]
This looks identical in Apophysis, so I don't believe this is a bug. Please verify for yourself in Apo.

**Comment by MAD-OVERLORD** [comment]
Shouldn't we not take the grandfather flam3 as the de facto standard?
`flam3-render < PieVariationBug.flam3`

![00000](https://cloud.githubusercontent.com/assets/16815857/12906317/54288036-cedf-11e5-84ae-bad1a41af02d.png)

`emberrender --opencl --in=PieVariationBug.flam3 --out=Test.png`

![pievariationbug flam3](https://cloud.githubusercontent.com/assets/16815857/12906371/d85edddc-cedf-11e5-81fe-e4178824af46.png)

**Comment by mfeemster** [comment]
Good catch, but I prefer Apo over flam3. Both are dead codebases, but flam3 is "deader" =)

I've examined all of the code between the three and they seem identical, so I am not sure what is wrong. Regardless, Apo and Fractorium are correct:

You have a value of pie_thickness="0.249187"

So you would expect the thickness to be about one quarter of the circle. If you want the greater thickness like flam3, just increase pie_thickness to about 0.75.

**Comment by MAD-OVERLORD** [comment]
@mfeemster 
"Deader" :D That is exactly like i feel me now after being over 24h awake :D 
Apophysis is not multiplattform as far as i know AND it is NOT in my sacred software repository like flam3 IS, 
BUT
i totally agree with you just based on the numbers and i found out what really the problem was, your godlike Fractorium probably uses integer values for the slices, since less then one slice probably makes no sense and Flam3 and Qosmic gave the artist a bit more freedom to express their stupidity, by assigning a float value to slice, so since i often do my artworks lightyears away from my brain, i did not account that and i apologize that i have wasted your time with that one.

Have a nice whatever you have there at the moment :)

**Comment by mfeemster** [comment]
Thanks for closing this, one follow up comment:

Good observation on the variable range. Apo added the concept of restricting variation parameters to certain ranges and types of inputs. flam3 had no such restrictions. So I implemented what Apo did since it seems more correct.

PS: Sleep deprivation is extremely bad for you, so go to bed.
