### ISSUE TITLE
Several Problems with the newest Commit(on compiling)

### ISSUE THREAD

**Issue by MAD-OVERLORD** [mfeemster/fractorium#61]
Maybe not of interest, but just to have it noted:
The last time i could compile without `export QT_SELECT=qt5`, now it craps out because of:
`/tmp/fractorium/Builds/QtCreator/EmberAnimate/EmberAnimate.pro:15: Unknown replace function: absolute_path`

With `export QT_SELECT=qt5` set, it craps out because of:
`/tmp/fractorium/Builds/create-symlinks.sh "/tmp/fractorium/Builds/lib" "/tmp/fractorium/Builds/include"`
`/bin/sh: 1: /tmp/fractorium/Builds/create-symlinks.sh: Permission denied`
`make: *** [symlinks] Fehler 126`
------>You probably shouldn't work on windoze, the insecure stone age NTFS can't handle EXT4 file permissions and execute bits, so you ruin every shell script and bin that way.
(Do you miss anything with Codeblocks IDE on Linux, that you still haven't liberate yourself from Windoze and the pay to play 64bit VC Studio? BTW. even for windoze open sourcers the ["hey i have a awesome free software project, but you have to buy micro+soft crap to be able to practice your most fundamental human rights"](https://github.com/mfeemster/fractorium/wiki/Building) may be a little bit strange and could be circumvented with Codeblocks IDE :D)

**Comment by mfeemster** [comment]
So are you unable to compile at the moment?

Are you saying that this repository keeps file permissions on each file and I have accidentally changed it? If so, can you please reset the permissions to what they should be and submit a PR?

-----

First, I am the lead on this project, so I'll be choosing the development methods and tools. Windows is my preferred OS and that is not going to change any time soon, if ever.

Second, I tried Codeblocks on Linux and had some trouble with it which I can't exactly remember. Regardless, it doesn't matter, because on Linux, myself and the rest of the developers have used Qt Creator which works fine and is free.

Third, Visual Studio is free on Windows, so you don't have to pay to build. You can also use Qt Creator on Windows. If you have problems building with that after following the detailed build instructions, please fix the project files and submit a PR.

Fourth, I provide an installer for Windows, so worrying about building is a non-issue for for everyone whom I've interacted with who is using on Windows.

**Comment by MAD-OVERLORD** [comment]
No Sir, i just wanted to post the problem for other users, which may not be that much Unix savvy.

I do not particularly know what github exactly does, since i am totally fresh meat here, but since any good and the most servers in this world are unix based, they will have some form of a more secure file system with proper file permission and execute bit management, therefore yes, i guess github will do exactly that for you, and when you download your repo onto a NTFS file system all scripts and bins will be stripped off from these extra attributes and when you're lucky, github checksumms the files and reuploads only the ones you have actually touched/changed and not all, so no need to feel attacked when i suggested you to work on Linux for multiplattform projects, that was a totally serious advice to circumvent such problems and was not part of my usual fun os flamewar ;)
The other way round you will have less problems, the only thing you have to watch out, when working on Linux for Microsoft is, that you must pay attention to never write a space at the beginning or at the end, and after a while, when we have completely forgotten windoze and its stupid limitations, it is a good advice to write a filename compatibility script which removes all these special chars a windoze doesn't like in file names as well to shorten everything to 255 chars, then you will be absolutely fine.
That you don't ruin every software you have already for Linux or that you create severe Securety Holes by for example saving a portion of your linux system just like so on a NTFS or FAT32 disk, then copying it back or something like that, my advice is to save anything always in a tar or AFAIK also a zip should work to preserve these extra file attributes.
That is of course just totally over complicated bullshit you may think, but if you ever have to deal with website hackers, cats, or grandmothers which want to learn computer writing at the age of 80, you will immediately understand, that it was absolutely worth the time you invest in chown/chmod and the file permissions ;D

I am a bit new here, i will have to study first how we even do that PR thing, but i will try as soon as possible, even if i had contributed every piece of my free time this week already today.

***
WHAT?, since i wrote 0,0 lines of code i really thought i was the lead here, oops damn i forgot, i am on a open source site, where the rules are totally inverted from normal capitalism, sorry for that :D 

Ok, i will give it a shot too some day, the only free IDE i somehow don't like is eclipse, even if many swear on that java based crap

Your words in the link i have read was:
`Sadly, the free version of Visual Studio does not support building x64 targets. You are welcome to build for x86, but understand that the CPU performance will be significantly lower than what you experience with the executable contained in the installer.`
And if i am allowed to be a bit stallmanish, it's not free/open, it's for free, gratis, so who knows what for NSA trojans you compile in each and every software you made with that, have you ever thought about that? :S 

That's somehow sad, so they have to much time for getting numb and dumb in front of their cinema sized tv screens :D

**Comment by mfeemster** [comment]
Good advice, for files which are expected to run, such as scripts, I will only edit them on my Linux VM.

Thanks for catching the blurb about x64! I have removed it. I totally forgot I had written that. It was for VS 2010 and is no longer true. x64 support is now included in the Express Edition.

**Comment by MAD-OVERLORD** [comment]
Sadly i have too much to do at the moment to learn all the basics of github to do a fork and PR and all that stuff, and besides that, i have only my gaming machine at the moment, which i am not considering a secure development environment, with all that closed source stuff running on it, so i don't want to risk a potential attack vector to your project, even if all my cautions make no sense at all, when you are doing stuff on windoze with closed source compilers, but it's just the way i work.
I'm that much paranoid, that i don't even trust the aluminium foil hats for several medical and technical reasons, ya know :D 
Compiling still doesn't start without setting the execute bit, so if you extract that zip in your VM and compare the content with the convenient MELD(Diff GUI)(sudo apt-get install meld), it should be save to use it, if the content is equal.
[create-symlinks.zip](https://github.com/mfeemster/fractorium/files/125823/create-symlinks.zip)

**Comment by gambhiro** [comment]
I just added a chmod to `package-linux.sh`. That's a good place for any hacks that help it compile on Linux.

@MAD-OVERLORD If we want to use it on Linux, it's up to us to make it work. @mfeemster listens and helps where he easily can, but really it's up to us to make it work for us.

**Comment by mfeemster** [comment]
I have re-worked the build and I believe this is fixed.
