### ISSUE TITLE
New attribute in <flame> tag in recent flam3

### ISSUE THREAD

**Issue by nonno-cicala** [mfeemster/fractorium#74]
I built flam3 recently and flam3-genome now creates flames which can't be opened by fractorium because of a new attribute in the <flame> tag: palette_interpolation="hsv_circular" .

This is an example from a random flame (it's the last attribute):
`<flame version="FLAM3-LNX-v3.1.1-2-ge080154-dirty" time="0" size="100 100" center="-0.924781 0.688638" scale="22.0444" rotate="0" supersample="1" filter="0.5" filter_shape="gaussian" temporal_filter_type="box" temporal_filter_width="1" quality="1" passes="1" temporal_samples="1000" background="0 0 0" brightness="4" gamma="4" highlight_power="-1" vibrancy="1" estimator_radius="9" estimator_minimum="0" estimator_curve="0.4" gamma_threshold="0.01" palette_mode="step" interpolation_type="log" palette_interpolation="hsv_circular">`

If I remove that `palette_interpolation="hsv_circular"` it works.

Could this palette interpolation be implemented in fractorium? If not (or you don't have time) you could just skip that attribute with a warning and an explanation in the Info tab.

**Comment by mfeemster** [comment]
Is this a recent update to the flam3-genome code? Where did you get it from?

**Comment by nonno-cicala** [comment]
I don't know exactly how recent is that new attribute, but the code [here](https://github.com/scottdraves/flam3) has been updated the 4th August 2015.

**Comment by mfeemster** [comment]
Well I'll be damned, it lives! Thanks for the link, I thought flam3 died a long time ago. Good to see Scott working on it again.

In his change log, he added that feature just last year after a 4.5 year break. So it's not in the Fractorium codebase. I'll have to add it.

**Comment by mfeemster** [comment]
Fixed. Rebuild and verify.

**Comment by nonno-cicala** [comment]
Fix confirmed, thanks!
