### ISSUE TITLE
Build system problems [make]

### ISSUE THREAD

**Issue by nonno-cicala** [mfeemster/fractorium#75]
Since commit 6ff8aa072227ead106e58f356e0a44f34d7cc531 I haven't been able to build fractorium any more.

This is the output of `make -j1`, after the first try didn't work, with the latest commit ( 63f933de0e1efdf11d1c365cdf88fb9236cb509f ): 
[buildfail160226.txt](https://github.com/mfeemster/fractorium/files/148768/buildfail160226.txt)

And somehow the script `./Builds/create-symlinks.sh` lost its execute permission. Is there a reason for that? ( @gambhiro if there was a problem with the permission I suppose it could be fine to just call sh, like [this](https://github.com/mfeemster/fractorium/files/148782/main.pro.patch.txt) )

**Comment by mfeemster** [comment]
Do a clean, then build. It's probably pointing to old libs from the last install. @gambhiro had that problem too once when I added some new functions.

This points to a bigger problem though and it scares me. It means whenever you pull fresh and build, you're not really linking to what you just built.

---

Regarding the permissions, I thought this was fixed:

https://github.com/mfeemster/fractorium/pull/66

---

I would really like to go through the Linux builds with a fine tooth comb, but just don't have the time. So when building on Linux, you're sort of on your own.

Anyone is welcome to look into this.

**Comment by nonno-cicala** [comment]
The permissions were correct yesterday, the execute bit disappeared in commit 6ff8aa072227ead106e58f356e0a44f34d7cc531 :)
---
I already tried to build from within a fresh dir, so I thought it could be linking against the libraries installed in /usr/lib , uninstalling fractorium solved the problem! So you are right, the build system isn't linking to what you just built.

Thanks!

**Comment by mfeemster** [comment]
Something is terribly wrong then. The commit you linked did not include the .sh file, so you are saying github modified a file that I did not commit? How is that possible? Please clarify, thanks.

---

Glad you were able to confirm my suspicions. I am reopening this and leaving it open until it's fixed.

So this issue becomes:

make needs to place its output libs in bin/release or bin/debug and then link the executables to those. make should *not* be linking to the system location.

make install should then copy those to some system location.

**Comment by mfeemster** [comment]
I think I know what's wrong. It's looking in the system lib dir before looking in the project output dir. @gambhiro can you verify this is the case and if so, make it look in the output dir first before searching the system? Thanks.

**Comment by nonno-cicala** [comment]
About the permission I think I can't be clearer than this:
![fractorium-permission](https://cloud.githubusercontent.com/assets/3453679/13373108/4d851194-dd5e-11e5-90e5-bb7ef90114f1.png)

**Comment by nonno-cicala** [comment]
I tried a brutal:
`$ sed s:-L/usr/lib[[:graph:]]*\ ::g -i Builds/QtCreator/defaults.pri`
obtaining 
[this](https://github.com/mfeemster/fractorium/files/149481/defaults.pri-nousrlib.patch.txt), and it worked without linking to old binaries (I tried putting libEmberCL.so and libEmber.so from an old build, v.0.9.9.3, in /usr/lib beforehand).
Why are those paths explicitly there? Without them it searches there at low priority and links correctly on my system.

**Comment by mfeemster** [comment]
I am going over the qt build files for the first time in a long time. This is insanity, I'm rewriting almost all of it. I'll do a commit that will fix the issues.

**Comment by gambhiro** [comment]
The permission bit on the `.sh` file tends to be lost when @mfeemster commits from Windows, I suppose just a difference between the file systems. I don't know how to configure the equivalent of `./Builds/create-symlinks.sh` in qmake, I was satisfied with an explicit `chmod` in `package-linux.sh`.

As for the library order, it will be probably the order of lists in the `.pro` files.

**Comment by mfeemster** [comment]
Everybody hold off on any work here, I am re-writing most of it.

**Comment by mfeemster** [comment]
I have removed the symlinks file. Please update and rebuild. I am hoping it builds out of the box, but if not, please let me know of any remaining problems. Thanks.

**Comment by gambhiro** [comment]
Related: #79

**Comment by nonno-cicala** [comment]
It builds out of the box on my Gentoo, but it still links with the system libraries first.
The sed line I wrote before fixed the problem for me:

> `$ sed s:-L/usr/lib[[:graph:]]*\ ::g -i Builds/QtCreator/defaults.pri`

Now make install just installs, thanks!

**Comment by mfeemster** [comment]
Sorry to hear it didn't fully work. I really want to get this correct. I don't know sed, so can you tell me exactly what that command is doing? That will help me repro and ultimately fix it.

**Comment by nonno-cicala** [comment]
That command means:

> substitute (s) -L/usr/lib followed by any non-negative integer number (*) of characters ([[:graph:]]) and a space (\ ) with nothing (there is nothing between the last two colons), and do that everywhere in the file (g), then save the result in place (-i) of the original file

The result is [this](https://github.com/mfeemster/fractorium/files/155095/defaults.pri-nousrlib2.patch.txt).

My thought was just to remove any explicit reference to the system paths, so they are automatically searched after everything else.

**Comment by mfeemster** [comment]
Ah ok, I understand now, thanks.

After looking at that, I am going to rework some of the link statements. Not every project needs to link to all of those. I'll try a few things on my system and commit later tonight.

**Comment by mfeemster** [comment]
I've removed the specific paths from the .pri file and it builds fine on my Linux Mint VM. Please rebuild and let me know if it works.

**Comment by nonno-cicala** [comment]
It worked and used the correct libraries.
All the issues here seem to be fixed then, thanks a lot!
