### ISSUE TITLE
DE filtering not working on scaled fractals or high quality

### ISSUE THREAD

**Issue by MightyLight** [mfeemster/fractorium#76]
I don't know if this is supposed to happen with DE filtering, if that is the case I'm sorry for opening this issue. I rendered a flame with a DE Filter max radius of 11 and scaling of 2 (for a total of 2000x2000) and the DE Filter effect was gone. 
This is the screenshot of the main window
![de filtering](https://cloud.githubusercontent.com/assets/10198835/13366257/f9c87a1e-dcb8-11e5-8b72-2e18e383de9a.png)
And this was the render result (quality = 30000):
![flame_2016-02-26-003731_10](https://cloud.githubusercontent.com/assets/10198835/13366373/7c6d181c-dcb9-11e5-84ef-13d3d2cdff61.png)
Made a test render with another flame afterwards and got the same result. Rendering with scaling 1 and the same quality got this:
![flame_2016-02-26-003731_11](https://cloud.githubusercontent.com/assets/10198835/13366478/282f44c2-dcba-11e5-9426-1498065ba358.png)
A little improvement, but it's now quite right, lowering the quality to 1000 rendered the exact flame I got on the first screenshot. 
 Again, I'm very sorry if this is me not understanding how DE filtering works.

**Comment by mfeemster** [comment]
If I am understanding your question correctly, this is not a bug and is behaving exactly as designed.

DE is for blurring low hit areas so they look less noisy. High hit areas already have lots of information, so they don't need much blurring. The difference you are seeing is between a low quality preview render, where almost the entire image is a low hit area and will therefore be heavily blurred vs. a high quality final render where almost the entire image is a high hit area and will therefore not be blurred much at all.

Further explanation here:

https://github.com/scottdraves/flam3/wiki/Density-Estimation

BTW, using a width greater than 9 is unlikely to add any value. Large width filters greatly slow down the density filtering step on the GPU.

**Comment by MightyLight** [comment]
Thanks a lot Matt. I should look into using some kind of blur for the background then.

**Comment by MightyLight** [comment]
Just a final thought, what I'm doing on most of this flames is lowering the gamma threshold to 0 or almost 0, so the flame continues in the background, although as you say, as a very low hit areas, that causes noise. My intention with using DE filtering was to remove that noise,so if I understand this correctly by increasing both resolution and quality this noise now has high hit area and the DE filter doesn't consider it noice anymore. I don't think this is how it should work, since the increase in both resolution and quality should increment the hits in every pixel, the areas with noise still have proportionally less hits. Is flam3 using a fixed hit amount?

**Comment by mfeemster** [comment]
Increasing resolution usually will not change the DE effect, but quality definitely will. That's because quality is measured in iterations PER pixel.

**Comment by MightyLight** [comment]
I see, but DE filtering shouldn't be done on pixels with low amount of hits in relation with the amount of hits on the flame? I find it odd if that's not how flam3's DE filtering is implemented. Even if DE filtering checks for a fixed amount of hits, if the algorithm divides the amount of hits it checks by some number in relationship with the quality of the render it should work fine for high quality renders too. 
 Probably I should be talking with the flam3 maintainers but I don't know if this is something on their end or ours, or even if it is a problem for other people (I guess not)

**Comment by mfeemster** [comment]
No, the opposite. DE is done *more* on lower hit pixels, and less on higher hit pixels. And it does work fine for high quality renders, it just blurs them less because the blurring is not needed as much.

Anyways, this algorithm is well implemented and tested with the results verified in hundreds of thousands of works of art, so there isn't any more to do on it. I am going to close this issue.

Just play with the numbers and you'll see its effect. Always remember you can disable it completely by setting max DE filter width to 0.

**Comment by MightyLight** [comment]
I just wanted DE filtering to smooth the noisy background on high quality renders, but I understand now that's not the goal of DE filtering. Thanks a lot for your time Matt.
