### ISSUE TITLE
CTRL + Z / Undo unlocking affine scale and rescaling to original size.

### ISSUE THREAD

**Issue by MightyLight** [mfeemster/fractorium#77]
Undoing always unlocks affine scale and returns the transforms to the original size.

**Comment by mfeemster** [comment]
Fixed. If you are building from source, please test. If not, wait for the next release and close this if looks good to you.

**Comment by MightyLight** [comment]
I've been always scared of building from source since it looks complicated but, oh well, let's give it a try. I've been interested in contributing for a while now and might as well start testing.

**Comment by mfeemster** [comment]
Hold off for a bit. I'm making major changes to the build.

**Comment by mfeemster** [comment]
Update and build using the new instructions:

https://github.com/mfeemster/fractorium/blob/master/Data/BuildGuideQtCreator.md

**Comment by MightyLight** [comment]
It's woking fine there
