### ISSUE TITLE
cannot find -lOpenCL

### ISSUE THREAD

**Issue by gambhiro** [mfeemster/fractorium#79]
Thanks for the latest commit! I'm seeing the old friend now:

```
g++ -m64 -Wl,-O1 -s -shared -o libember.so Affine2D.o DllMain.o Ember.o EmberPch.o RendererBase.o Renderer.o VariationList.o  -L/usr/lib -ljpeg -lpng -ltbb -lpthread -L/usr/lib/x86_64-linux-gnu -lxml2 -lGL -lOpenCL
/usr/bin/ld: cannot find -lOpenCL
```

Even though it is in `/usr/lib/x86_64-linux-gnu/libOpenCL.so.1`

```
$ ls /usr/lib/x86_64-linux-gnu/libOpenCL* -l
lrwxrwxrwx 1 root root    18 Jun 10  2015 /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 -> libOpenCL.so.1.0.0
-rw-r--r-- 1 root root 43408 Jun 10  2015 /usr/lib/x86_64-linux-gnu/libOpenCL.so.1.0.0
```

I remember now I couldn't set the compile options that would let it see it as `.so.1`, and I resorted to symlinking it as `.so` in the build folder.

**Comment by nonno-cicala** [comment]
I think it is a problem on your side if ld cannot find a system library, not a problem of fractorium.
Maybe you could try something like:
`sudo ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 /usr/lib/libOpenCL.so`

**Comment by mfeemster** [comment]
I was also going to say that. I think the right approach is for you to create a symlink as @nonno-cicala suggested.

Perhaps there might be a bigger issue on your system? From my limited understanding of linux, most libraries have a version in their filename, so there is a non-versioned link to them.

mylib.so is a symlink that points to mylib.so.1, that way programs only have to look for mylib.so

I've also ready that sometimes you have to run ldconfig to get this setup right? Not sure about that though.

Either way, I'd rather not pollute an already complex build process with more steps. Let me know what you think.

**Comment by gambhiro** [comment]
Yes, this is a problem with the package that installs opencl, not with fractorium. The package **should** include a `.so` symlink, but it doesn't.

`sudo` is unfortunately out. The Launchpad autocompile has to build fractorium by calling `qmake` and `make` in a (minimal) fresh system, with the declared dependencies installed.

At the time, all I could come up with is to symlink the lib to the build folder with an `.so` name.

**Comment by mfeemster** [comment]
I'm not familiar with launchpad. So where/what is this minimal system that it builds on? Is it your home machine or a remote server that launchpad provides? Perhaps I can give it a try on my machine.

Which package do you think should have been responsible for creating the symlink? Because I know you installed a few. If we can track it down, perhaps we can contact the maintainers.

**Comment by gambhiro** [comment]
Launchpad builds on online servers. It starts a clean environment for each build, installs the declared deps, runs the autobuild, and lets me know when it failed or succeeded. One can do a similar procedure for local builds, but it only serves testing purposes, to get the source tarball ready for Launchpad.

`ocl-icd-libopencl1` provides `/usr/lib/x86_64-linux-gnu/libOpenCL.so.1`

http://packages.ubuntu.com/wily/ocl-icd-libopencl1
https://launchpad.net/ubuntu/+source/ocl-icd

`nvidia-opencl-icd-352` provides `/usr/lib/i386-linux-gnu/libnvidia-opencl.so.1`

http://packages.ubuntu.com/wily/nvidia-opencl-icd-352
https://launchpad.net/ubuntu/+source/nvidia-graphics-drivers-352

Please open an issue with them if you have the energy.

**Comment by mfeemster** [comment]
So there is no way to manually configure anything on the launchpad server? What if someone is building something exotic?

**Comment by gambhiro** [comment]
It has to be done with the config tools (qmake, cmake, autotools, ... they all "compile" to Makefiles), setting everything up such that a `make` call will perform everything.

**Comment by nonno-cicala** [comment]
I checked a Mint 17.3 Live installation DVD (based on Ubuntu 14.04 Trusty) and:

> mint@mint ~ $ dpkg -S /usr/lib/x86_64-linux-gnu/libOpenCL.so
ocl-icd-libopencl1:amd64: /usr/lib/x86_64-linux-gnu/libOpenCL.so

It provides the right file there (as you can check [here](http://packages.ubuntu.com/trusty/amd64/ocl-icd-libopencl1/filelist)), and linking a test file with just -lOpenCL found the library.

@gambhiro , you haven't listened to the @MAD-OVERLORD , He told you to build the package for the LTS, you are paying for your sin. :D

**Comment by mfeemster** [comment]
Great catch @nonno-cicala 

If the latest fixes it, then we should just have people use that.

**Comment by gambhiro** [comment]
wow, indeed `ocl-icd-opencl-dev opencl-headers` it is. It builds successfully!

I'm busy with sth else but I will make adjustments and test building on Launchpad.

**Comment by mfeemster** [comment]
I will add those to the linux build steps then. Thanks for verifying.

**Comment by mfeemster** [comment]
I've added them as well as removed the dbus package. That was left over from some other old stuff that was unrelated.
