### ISSUE TITLE
Build problems on Windows

### ISSUE THREAD

**Issue by MightyLight** [mfeemster/fractorium#80]
This is probably a problem on my end but I can't figure it out on my own. The error message at build is this one:
`C:\Users\Paulo\Desktop\repos\fractorium\Source\Ember\EmberPch.h:65: error: C1083: Cannot open include file: 'libxml/parser.h': No such file or directory`

The file is not there, it's in libxml2/libxml, I checked EmberPch.h and as I though, it should check there since this is all 64 bits (kit is Qt 5.5.1 (msvc2013_64))

I thought maybe the qmake step is the problem? it is as follows:
`qmake: qmake.exe main.pro -r -spec win32-msvc2013`

**Comment by mfeemster** [comment]
Did you follow my new build instructions exactly?

https://github.com/mfeemster/fractorium/blob/master/Data/BuildGuideQtCreator.md

**Comment by MightyLight** [comment]
Oh damn, I swear to god I saw you changed the instructions on a commit but I don't know why my page didn't update correctly. Let me check what can i do differently.

**Comment by mfeemster** [comment]
Start over completely. Those new instructions should help you get up and running quickly.

**Comment by MightyLight** [comment]
Yes, I figured that will be the best. Will close this as soon as I make the Qt creator stage.

**Comment by MightyLight** [comment]
This could be my lack of experience but I found the instruction to get the tbb from the "open source download" confusing I tried with the normal download thinking it was "open source" instead of looking for the source, so makedeps.bat didn't worked until I realized this.
Then, when building using Visual Studio, FractoriumInstaller didn't open because I didn't had wix. I installed it and this time it opened fine but the build failed:

```
>------ Build started: Project: FractoriumInstaller, Configuration: Release x64 ------
8>	C:\Program Files (x86)\WiX Toolset v3.10\bin\candle.exe -dGpuType=AMD_NVIDIA -d"DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\\" -dSolutionDir=C:\Users\Paulo\Desktop\repos\fractorium\fractorium\Builds\MSVC\VS2013\ -dSolutionExt=.sln -dSolutionFileName=Fractorium.sln -dSolutionName=Fractorium -dSolutionPath=C:\Users\Paulo\Desktop\repos\fractorium\fractorium\Builds\MSVC\VS2013\Fractorium.sln -dConfiguration=Release -dOutDir=C:\Users\Paulo\Desktop\repos\fractorium\fractorium\Builds\MSVC\VS2013\..\..\..\Bin\x64\Release\ -dPlatform=x64 -dProjectDir=C:\Users\Paulo\Desktop\repos\fractorium\fractorium\Builds\MSVC\Installer\ -dProjectExt=.wixproj -dProjectFileName=FractoriumInstaller.wixproj -dProjectName=FractoriumInstaller -dProjectPath=C:\Users\Paulo\Desktop\repos\fractorium\fractorium\Builds\MSVC\Installer\FractoriumInstaller.wixproj -dTargetDir=C:\Users\Paulo\Desktop\repos\fractorium\fractorium\Bin\x64\Release\ -dTargetExt=.msi -dTargetFileName=Fractorium_Beta_0.9.9.4.msi -dTargetName=Fractorium_Beta_0.9.9.4 -dTargetPath=C:\Users\Paulo\Desktop\repos\fractorium\fractorium\Bin\x64\Release\Fractorium_Beta_0.9.9.4.msi -out obj\x64\Release\ -arch x64 -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixUIExtension.dll" Product.wxs
8>C:\Users\Paulo\Desktop\repos\fractorium\fractorium\Builds\MSVC\Installer\Product.wxs(168,0): error CNDL0150: Undefined preprocessor variable '$(env.QTDIR)'.
8>Done building project "FractoriumInstaller.wixproj" -- FAILED.
========== Build: 6 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
```

Just finishing I realized Visual Studio and QtCreator was a bifurcation on the build path, I thought it was a sequential instruction. QtCreator didn't throw any errors, but executing fractorium.exe tells me libxml2.dll is missing although I have obviusly Qt installed. What I'm missing? I could copy it there of course, but it seems odd.

**Comment by mfeemster** [comment]
This is why it always helps to have an extra set of eyes on this stuff, thanks for going over it. I will clarify it later tonight and also examine the libxml2 problem and report back here.

**Comment by MightyLight** [comment]
I'm glad to help.
I forgot to paste the errors on the Visual Studio build:

`Error	5	error MSB6006: "cmd.exe" exited with code 3.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	170	5	Fractorium
`


and:

`Error	24	Undefined preprocessor variable '$(env.QTDIR)'.	C:\Users\Paulo\Desktop\repos\fractorium\fractorium\Builds\MSVC\Installer\Product.wxs	168	1	FractoriumInstaller
`

**Comment by mfeemster** [comment]
The build guide has been fixed. I've also done another commit. So update your repository, and refresh the page and try it again.

**Comment by MightyLight** [comment]
"refresh the page" that's harsh haha.
QtCreator worked perfectly with install argument. 
I'm going to try the Visual Studio build later, I'm downloading the Qt add-in for visual studio, since all this time I though that was included in the Qt default install.

**Comment by MightyLight** [comment]
Visual Studio works fine too. It still has the error about the preprocessor variable but I didn't found any problem with that.

**Comment by mfeemster** [comment]
Sounds good, don't worry about Wix. But just to be sure, did you add the QTDIR system environment variable?

**Comment by MightyLight** [comment]
Yes
