### ISSUE TITLE
Color curves not smooth enough

### ISSUE THREAD

**Issue by MightyLight** [mfeemster/fractorium#81]
I wasn't sure at first if this was a problem or not, but I'm starting to feel like it is, or at least, is bothering me while I use Fractorium. When modifing the color curve the first movement one does "snaps", making a dramatic effect on the fractal that successive movements don't replicate, thus, it's quite hard to manage to edit the behavior of the the color on the fractal (I mostly use photoshop on my final renders just to manipulate the color curves). My problem with this mostly is that I want to make a smooth transition and the first modification of the curve is too dramatic for my taste. 

Also, and I don't know if this is the way it's intended or not, but as the color curves are on the transform color tab, I though this color curves could deal with the color only in the transform. This would be both good and bad since modifing each transform's curve would be tiresome, maybe a "modify all curves" could do the trick. Again I'm not sure if this was the intended behavior, if not, maybe the color curves should be on the flame, or palette tab.

**Comment by mfeemster** [comment]
I've noticed the same thing a while back and it perplexed me as well. The code was copied directly from Apophysis, reworked to fit into my design, so the results should be the same. However, there is a chance I screwed it up somehow.

Please perform this test: Take a basic flame that renders the same in Fractorium and Apophysis. Make the same small adjustment to the curves in each one and verify the results look the same. If so, try some greater movements, but keep them the same between each. See if any differences show up in the final image and report back here.

I did this test while developing and I remember it being fine. But who knows, I could have screwed something up.

---

Regarding the placement of the curves control, you are correct. It's misleading that it's under xforms when it has nothing to with them. Curves adjust the color after all iteration is complete, so there is no concept of xforms at that point in the process. A better placement of the control would be on the palette tab. It sounds like you'd be in favor of that? Please confirm and I'll do it.

**Comment by MightyLight** [comment]
Oh, you are right, it works the same as Apophysis. That's too bad, this is one of the reasons people use chaotica to do the post-work. 

And yes, I would be on favor of placing the curves on the palette tab.

Thanks a lot for your attention Matt

**Comment by mfeemster** [comment]
Ok, I'll do some comparisons with Chaotica. I think people mostly use it because it renders faster and with a higher quality than Apo. It also supports animations now.

I'll try moving the curves control in the near future.

**Comment by MightyLight** [comment]
I think shaders on Chaotica are  a big part too, at least that's what I got from ChaosFissure.

**Comment by mfeemster** [comment]
I have moved the curves control to the Palette tab with the latest commit.
