### ISSUE TITLE
Fractorium crashes when openCL is switched on

### ISSUE THREAD

**Issue by perrelet** [mfeemster/fractorium#82]
Hey there,

So very grateful for this project - the fractal flame community has never made it anywhere near this far with a fully functioning gpu flame renderer before. This is freaking exciting stuff - history in the making!

...If only it would work for me :(

When I click "Use openCL" - the application immediately stops working and crashes.

I'm using the .msi installer on windows 7 64-bit.

I have a quadro k2000m GPU

Any suggestions? Is there an older build I can test for you?

Many blessings and look forward to hearing any ideas,

J :)

**Comment by mfeemster** [comment]
Hi perrelet, thanks for the kind words. Sorry to hear things didn't work out for you.

Did you install the latest drivers for your GPU? If not, please do that and try again.

Can you please post a screenshot of the options dialog too? Thanks.

**Comment by perrelet** [comment]
Hey, thanks for the rapid reply.
I did indeed update the official nvidia drivers before install.
Here's a link to screenshot and also the crash report from windows:
https://drive.google.com/folderview?id=0B-XQNjpS7wm5LUVCV2hEcnhDenc&usp=sharing
Hope that helps,
Jamie :)

**Comment by mfeemster** [comment]
Please post a screen shot of the _options _dialog__. I need it to see what other hardware you have that might be causing the problem.

Also, does that laptop use Nvidia Optimus? We've had serious problems with it that we were not able to resolve. If you have an hour to read:

https://github.com/mfeemster/fractorium/issues/64

**Comment by perrelet** [comment]
Hey there,

Oops - indeed the options dialog... Here it is:

![frac-options-dialog](https://cloud.githubusercontent.com/assets/7825147/13573034/732e400a-e475-11e5-9f1e-c5a384abd449.jpg)

As for optimus, I've seen related issues with things like spout - the dev team there went through an absolute nightmare because of it. I'll have a go at disabling it in the bios - will post back with updates.

Thanks a bunch :)

**Comment by mfeemster** [comment]
Sorry for not making this clearer in the documentation, I am currently working on a website that will gather all needed information for the user in a coherent way.

The first time you enable OpenCL, you must do it through the options dialog, not the toolbar. So check Use OpenCL, then:

Check Nvidia
Set Nvidia to primary
Uncheck Intel

Click Ok. If you see no errors or warnings, it means you are using OpenCL.

I checked the specs on your card, it might not offer much performance over the CPU.

Last, the current version of 0.9.9.4 has some bugs. Using hexes in SP mode will crash the program, so avoid it until I issue a new release, which should be soon.

**Comment by perrelet** [comment]
Sweet Beans! It worked!

So for further clarification and for documentation:

The issue discussed **also** manifests when the "use openCL" checkbox is checked in options. I was able to fix this by changing the settings in nvidia control panel - setting fractorium to run from the nvidia gpu as default.

Thanks a million - super grateful, keep up the outstanding work!

Bless :)

**Comment by perrelet** [comment]
Oh dear, spoke to soon.

Although I have openCL working in the preview renderer. When I click Final Render I am unable to choose my gpu... eek.

![fract](https://cloud.githubusercontent.com/assets/7825147/13574887/08c77bec-e47e-11e5-9d3a-db28b81a1740.jpg)

Ideas?

**Comment by mfeemster** [comment]
Ah ok, good info, thanks. I didn't know Nvidia allows you to override that setting to force a specific application not to use Optimus.

@MAD-OVERLORD Give that a try if you're still having problems.

For final clarification in case you ever run on different hardware (again, I'll capture all of this in a website soon):

-When running Fractorium, you must specify a "primary" card which is the one connected to the display.
-If you have multiple GPUs, you can specify additional cards which are not connected to the display.
-When running on the command line, you can specify any card because the outputs are not displayed.

Re your screenshot: Check Use OpenCL =)

**Comment by perrelet** [comment]
Great stuff.

Only problem: The moment I click Use OpenCL - it crashes the thing...

Must be asking to gpu to perform a task in that moment?

**Comment by mfeemster** [comment]
Yes, you are correct. I will need to figure out a way around that.

If you want to hack it, you can close the program, go into %appdata%\fractorium and set these options, then restart the program:

[finalrender]
opencl=true
devices=1

All options are listed here:
https://github.com/mfeemster/fractorium/blob/master/Source/Fractorium/FractoriumSettings.h

Really sorry, you shouldn't have to hack like this. It's a bug I'll try to fix in the next release.

**Comment by perrelet** [comment]
Boom :)

No apologies necessary - super happy to be able to help the project out in anyway possible.

Also fyi: devices = 1, didn't work, I had to put:

devices=@Variant(\0\0\0\t\0\0\0\x1\0\0\0\x2\0\0\0\x1)

(I just copied it from the other options section where it had saved successfully)

**Comment by mfeemster** [comment]
Ah ok great, thanks for the info. Glad you're off and running. I will leave this issue open while I work on a solution.

**Comment by perrelet** [comment]
Dude - that render was lightning fast - even on this quadro.

Good job sir!

**Comment by mfeemster** [comment]
Since you are crashing only when Intel is selected, I am suspecting that you do not have the latest Intel OpenCL 1.2 or greater drivers installed. Can you install them and then try selecting Intel again under the devices list? If it can't render, that's fine, it should just report back and error and then you can select Nvidia. It should not crash the whole program though, however there is no way around it crashing if you have a driver that does not support at least OpenCL version 1.2.

**Comment by mfeemster** [comment]
Try to check your drivers like I mentioned above.

In the meantime, I've committed a workaround/fix. It works like this:

-Start from scratch by deleting your fractorium.ini in the install folder. A new install will be in this state.
-Successfully run with OpenCL in the main window using your preferred device(s).
-Restart the program, the main window will of course still be using OpenCL.
-Open the final render dialog, select Use OpenCL
-The device selected by default will be the one you successfully used in the main window.
-After you complete one render there successfully, when you exit the program your settings will be saved.

**Comment by mfeemster** [comment]
No response, so I am assuming my commit fixed the problem satisfactorily.
