### ISSUE TITLE
[Linux] Render fails un-minimizing the window

### ISSUE THREAD

**Issue by nonno-cicala** [mfeemster/fractorium#92]
If I start a final render then I minimize the window and reopen it the render fails on Linux.
Since the CPU use stays high when I minimize, before reopening the window, I suppose the problem happens when un-minimizing it.

**Comment by mfeemster** [comment]
Have you verified this on Windows too?

**Comment by nonno-cicala** [comment]
I haven't tried.
I forgot to mention I'm using the latest version from git: 5b6c62b95d3506d7f50702bca6eff097d37b3c25

**Comment by mfeemster** [comment]
Does this happen with lengthy renders or even with short ones? What quality value are you using? Does it happen on both CPU and GPU? When you say it fails, what do you mean? The program crashes? It outputs error text in the box at the bottom of the dialog? If so, can you post that here?

All of these are needed for any error report so please post them here.

**Comment by nonno-cicala** [comment]
It happened with every quality setting I tried (1000-6000), with every flame I tried (mostly randomly generated) with both CPU and GPU. When I say it fails I mean the program says something like:

> Rendering failed.
>
>All renders completed in: 2.48s.

It happens with latest git too ( 5aec58b ).

**Comment by mfeemster** [comment]
Found the problem and committed a fix. Please verify. Read on for details:

This was a tough one, so thanks for finding it! When that dialog is shown, I create the renderer it's going to use. On Windows, when you minimize the main window, then restore it, the show event is *not* fired. However on linux, it does get fired. So if you're in the middle of rendering, and minimize then restore, the renderer is stopped and recreated, which of course destroys what you were doing.

I placed a check in there to only create the renderer if one does not exist, or if the existing one is not currently running.

**Comment by nonno-cicala** [comment]
Seems fixed! Thanks for the quick fix and the explanation! :+1:
